rabbitmq:
  host: IP  # rabbitmq的主机名或IP
  port: 5672   # rabbitmq的端口
  user: guest   # rabbitmq的用户名，默认值为 guest,根据各自的情况进行更改
  password: guest # rabbitmq的用户名，默认值为 guest,根据各自的情况进行更改
minio:
  endpoint: IP:9000   # minio的主机名或IP,根据自己的情况修改
#  publicendpoint: oss-cn-beijing.aliyuncs.com #针对实际部署时s3内外网的区别，
  ak: 9QPAQ65R1SO1NDHNYESN  # minio 的ak ,根据自己的情况修改
  sk: X9MquX/OTU35GLApKJ8tEMqBcTcXc4WSKigkroUI  # minio的sk,根据自己的情况修改
  secure: false
  uploadbucket: upload
  draftbucket: draft
  staticbucket: static
  #dnslookup: true
  #region: oss-cn-beijing
statichost:   http://IP:9000 # minio的资源访问地址，根据自己情况修改
dgrpah:
  addr: IP:9080  # dgraph的主机名或IP,根据自己的情况修改,端口一般是默认值
mongodb:
  url: IP  # mongodb的主机名或IP,根据自己的情况修改
  db: docs
redis:
  url: IP:6379   # minio的主机名或IP,根据自己的情况修改,端口一般是默认值
  db: 0
elasticsearch:
  url: 127.0.0.1:9200
  enable: false
searchservice:
  host: IP
  port: 5005
editorurl: http://IP:5500/apps/editor
apiurl: http://IP:3000/apps/api
postapiurl:  http://IP:3000/apps/api/saveBack
queryapiurl: http://IP:3000/apps/api/query