version: "3.2"
services:
  drive_full:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/drive_full:${tag}
    container_name: drive_full
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
#    ports:
#    - 3000:3000
    networks:
      bisheng:
        aliases:
        - drive
  editor_app:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/editor_app:${tag}
    container_name: editor_app
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
#    ports:
#    - 5500:5500
    networks:
      bisheng:
        aliases:
        - editor_app
  editor:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/editor:${tag}
    container_name: editor
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
    environment:
      ADDR: editor
#    ports:
#    - 18000:18000
    networks:
      bisheng:
        aliases:
        - editor
  convert:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/convert:${tag}
    container_name: convert
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
    environment:
      ADDR: convert
#    ports:
#    - 5000:5000
    networks:
      bisheng:
        aliases:
        - convert
  nginx:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/nginx:free
    container_name: nginx
    privileged: true
    volumes:
    - ${basedir}/service/nginx/config:/config:rw
    - ${basedir}/service/nginx/temp:/temp:rw
    - ${basedir}/service/keys/keys:/keys:rw
    ports:
    - 80:80
    - 443:443
    restart: on-failure
    networks:
    - bisheng
networks:
  bisheng:
    external: true
